"""add body column

Revision ID: 309073dd36f9
Revises: 1cb2f7468b25
Create Date: 2024-07-04 07:50:43.822077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309073dd36f9'
down_revision = '1cb2f7468b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
